### PR TITLE
Must register the tinyg driver

### PR DESCRIPTION
**Pull request by anthonywebb**

### CODE REVIEW

**Comment by firepick1** [comment]
I was about to merge this until I realized that selecting TINYG will force /dev/ttyUSB0. Would you be OK with removing that line and setting up your firenodejs properties to /dev/ttyUSB0?

**Comment by anthonywebb** [comment]
I'm open to that, although I'm not real sure how the firenodejs properties work? I ammended my other commit with:

var devName = process.env.TINYG_SERIAL || "/dev/ttyUSB0"

I dont suppose that is what you meant?

**Comment by firepick1** [comment]
The process.env.TINYG_SERIAL solution was for testing. On this pull request, we need to do two things:

1) remove this line:
 that.model.rest.serialPath = "/dev/ttyUSB0";

2) that will break your code, but we fix it by launching firenodejs and setting the serialPath property from the web UI. Just go to Move accordion, click more... and set "serial path". Hopefully that should just work.

I'll merge the updated requested if #2 works for you (if it doesn't, we'll need to figure out what's going on...)

Thanks!

**Comment by anthonywebb** [comment]
That should work karl

**Comment by firepick1** [comment]
Anthony, thanks for all this hard work!

I'll go ahead and release it today. :D

**Pull request merged**
